apiVersion: v1
kind: ConfigMap
metadata:
  name: financials-tracker-2-frontend-config
  namespace: financials-tracker-2
  labels:
    app: financials-tracker-2-frontend
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  NUXT_API_BASE_URL: "http://financials-tracker-2-service.financials-tracker-2.svc.cluster.local/api"
  NUXT_HOST: "0.0.0.0"
  NUXT_PORT: "3000"
